VIA_ENABLE = yes
VIAL_ENABLE = yes
LT0_ENABLE = yes

QMK_SETTINGS = no
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = ws2812
MAGIC_ENABLE = no
MIDI_ENABLE = no
BLUETOOTH_ENABLE = no
BACKLIGHT_ENABLE = no
OLED_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = yes

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes

VIAL_ENCODERS_ENABLE = no

VIAL_INSECURE = no
